[RUNTIME] add ability to terminate/pause/resume a wasm program
eunomia-bpf/wasm-bpf pull request #84
Opened 2023-03-14 16:36 UTC by Officeyutong

I write a new function `run_wasm_bpf_module_async` to provide the ability to run a wasm program async and to control it.

- It has the same signature as `run_wasm_bpf_module`.
- This function will return immediately after calling, and leave the wasm program running in another thread
- It will return two handles. `WasmProgramHandle` provides ability to `pause`/`resume`/`terminate` a wasm program. `JoinHandle` provides the ability to wait for the finish of the wasm program. 
- I use the epoch interruption and the corresponding callback function (which will block the execution of the wasm program) to implement the functions. See https://docs.rs/wasmtime/latest/wasmtime/struct.Store.html#method.epoch_deadline_callback for details.
- I use mpsc channels to implement inter-thread communication. For example, send `ProgramOperation::Resume` signal to a hanging thread which is stuck on receiving the next operation.

2023-03-14 20:01 UTC, yunwei37 requested changes

2023-03-14 20:01 UTC, yunwei37 commented
nice job!

2023-03-15 02:01 UTC, Officeyutong commented on runtime/wasm-bpf-rs/tests/tick/.gitignore
> +tick.wasm
My  purpose is to ignore the tick.wasm under tick directory

2023-03-15 05:33 UTC, Officeyutong commented on runtime/wasm-bpf-rs/src/lib.rs
> +    // Now we force epoch interruption to be enabled
Fixed

2023-03-15 05:42 UTC, Officeyutong commented on runtime/wasm-bpf-rs/src/handle.rs
> +pub enum ProgramOperation {
Done

2023-03-15 06:21 UTC, yunwei37 approved these changes

2023-03-15 06:21 UTC, merged